---
- name: Download & install Dropbox-Uploader
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/{{ backup_dropbox_uploader_version }}/dropbox_uploader.sh
    dest: /usr/local/bin/dropbox_uploader
    owner: root
    mode: "0755"
    force: true

- name: Install age
  install_age:
    minversion: v1.3.0

- name: Install bin/mkbackup
  ansible.builtin.template:
    src: mkbackup
    dest: "{{ jwodder_root }}/bin/mkbackup"
    owner: "{{ admin_user }}"
    mode: "0755"

- name: Install share/backup.exclude
  ansible.builtin.copy:
    src: share/backup.exclude
    dest: "{{ jwodder_root }}/share/backup.exclude"
    owner: "{{ admin_user }}"
    mode: "0644"

- name: Store Dropbox credentials
  ansible.builtin.copy:
    dest: "{{ jwodder_root }}/etc/secret/dropbox_uploader"
    content: |
      CONFIGFILE_VERSION=2.0
      OAUTH_APP_KEY={{ backup_dropbox_oauth_app_key | quote }}
      OAUTH_APP_SECRET={{ backup_dropbox_oauth_app_secret | quote }}
      OAUTH_REFRESH_TOKEN={{ backup_dropbox_oauth_app_refresh_token | quote }}
    owner: root
    group: root
    mode: "0600"

- name: Store backup recipient pubkey
  ansible.builtin.copy:
    dest: "{{ jwodder_root }}/etc/backup-recipient.txt"
    content: |
      {{ backup_recipient_pubkey }}
    owner: "{{ admin_user }}"
    mode: "0644"

- name: Configure systemd units
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/systemd/system/{{ item }}
    mode: "0644"
  with_items:
    - mkbackup.service
    - mkbackup.timer
  register: backup_units

# This has to run before we can enable the timer, so using a handler isn't an
# option here.
- name: Reload systemd  # noqa: no-handler
  ansible.builtin.systemd:
    daemon_reload: true
  when: backup_units is changed

- name: Enable & start systemd timer
  ansible.builtin.systemd:
    name: mkbackup.timer
    enabled: true
    state: started
