[update-dns]
ipv4 = true
ipv6 = false
domain = "{{ dynamic_dns_domain }}"
subdomain = "{{ dynamic_dns_subdomain }}"
digital_ocean_token = "{{ digitalocean_token }}"

[dailyreport]
sender = "{{ dailyreport_sender }}"
recipient = "{{ dailyreport_recipient }}"
mailbox = "/var/mail/{{ admin_user }}"
disks = {{ dailyreport_disks | tojson }}

[outgoing]
method = "mailgun"
domain = "{{ mailgun_domain }}"
api-key = "{{ mailgun_api_key }}"
