---
- name: Install thoth-utils for admin user
  community.general.pipx:
    name: thoth-utils
    source: git+https://github.com/jwodder/thoth-utils
    state: latest
  become: true
  become_user: "{{ admin_user }}"

- name: Create thoth-utils config file
  ansible.builtin.template:
    src: utils.toml
    dest: "{{ jwodder_root }}/etc/utils.toml"
    owner: "{{ admin_user }}"
    mode: "0600"

- name: Configure systemd units
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/systemd/system/{{ item }}
    mode: "0644"
  with_items:
    - dailyreport.service
    - dailyreport.timer
    - update-dns.service
    - update-dns.timer
  register: utils_units

# This has to run before we can enable the timers, so using a handler isn't an
# option here.
- name: Reload systemd  # noqa: no-handler
  ansible.builtin.systemd:
    daemon_reload: true
  when: utils_units is changed

- name: Enable & start systemd timers
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - dailyreport.timer
    - update-dns.timer
