#!/bin/bash
((EUID == 0)) || exec sudo "$0" "$@"

if [ "$1" = "--rsync-only" ]
then rsync_only=1
     shift
fi

ROOT=/var/backups/jwodder

set -eux
mkdir -p "$ROOT"

JWODDER_ROOT="$(dirname "$(dirname "$(readlink -f "$0")")")"

for dir in /home /srv/git "$JWODDER_ROOT"
do if [ -e "$dir" ]
   then rsync -avRF --delete --delete-excluded \
              --exclude="$JWODDER_ROOT/etc/secret" \
              --exclude-from="$JWODDER_ROOT/share/backup.exclude" \
              --exclude-from=<(find "$dir" -type d -exec test -e {}/.norsync ';' -prune -print) \
              "$dir" "$ROOT"
   else rm -rf "$ROOT$dir"
   fi
done

crontab -l -u {{ admin_user | quote }} > "$ROOT"/{{ admin_user | quote }}.crontab

[ -z "$rsync_only" ] || exit 0

cd "$ROOT/.."
TARBALL=/var/backups/`hostname`-`date -u +%Y%m%dT%H%M%SZ`.tgz
tar zcf "$TARBALL" "$(basename "$ROOT")"

/usr/local/bin/age -e -R /opt/jwodder/etc/backup-recipient.txt -o "$TARBALL.age" "$TARBALL"

/usr/local/bin/dropbox_uploader \
    -f "$JWODDER_ROOT/etc/secret/dropbox_uploader" \
    upload "$TARBALL.age" /Backups/

rm -f "$TARBALL" "$TARBALL.age"
