module(load="builtin:ompipe")

if (
    ($syslogfacility-text == "auth" or $syslogfacility-text == "authpriv")
    and ($msg contains "Failed" or $msg contains "Invalid user")
    and ($programname == "sshd" or $programname == "sshd-session")
) then {
    action(
        type="ompipe"
        Pipe="/run/authfail.sock"
        template="RSYSLOG_FileFormat"
    )
}
