#!/bin/bash
((EUID == 0)) || exec sudo "$0" "$@"

set -eux -o pipefail

if [[ ":$PATH:" != *":/usr/local/bin:"* ]]
then PATH="/usr/local/bin:$PATH"
fi

if [ "${1:-}" = "--rsync-only" ]
then rsync_only=1
     shift
else rsync_only=
fi

backup_root=/srv/scratch/backup/"$(hostname)"
mkdir -p "$backup_root"

for dir in /home /srv/git
do if [ -e "$dir" ]
   then rsync -avRF --delete --delete-excluded \
              --exclude-from=/usr/local/etc/mkbackup/backup.exclude \
              --exclude-from=<(find "$dir" -type d -exec test -e {}/.norsync ';' -prune -print) \
              "$dir" "$backup_root"
   else rm -rf "$backup_root$dir"
   fi
done

crontab -l -u {{ admin_user | quote }} > "$backup_root"/{{ admin_user | quote }}.crontab

[ -z "$rsync_only" ] || exit 0

cd "$backup_root/.."
outfile=/srv/scratch/backup/`hostname`-`date -u +%Y%m%dT%H%M%SZ`.tgz.age
tar zc "$(basename "$backup_root")" \
    | age -e -R /usr/local/etc/mkbackup/backup-recipient.txt -o "$outfile"

dropbox_uploader -f /usr/local/etc/mkbackup/dropbox_uploader upload "$outfile" /Backups/

rm -f "$outfile"
