---
- name: Install essential or useful software
  ansible.builtin.apt:
    name:
      - aptitude
      - bash-completion
      - bind9-host  # host
      - ca-certificates
      - command-not-found
      - curl
      - dma
      - fail2ban
      - fzf
      - git
      - htop
      - iputils-ping  # ping
      - jq
      - manpages
      - moreutils
      - mutt
      - net-tools  # netstat
      - netcat-openbsd  # nc
      - openssh-client
      - openssl
      - patch
      - pipx
      - plocate
      - procps  # ps
      - psmisc  # pstree
      - python3
      - python3-pip
      - python3-requests  # Required for `install_age` module
      - python3-venv
      - ripgrep
      - rsync
      - rsyslog
      - tmux
      - tree
      - ufw
      - unattended-upgrades
      - unzip
      - vim
      - wget
      - zip
    state: present
    update_cache: true

- name: Deny all incoming connections
  community.general.ufw:
    policy: deny
    proto: any
    direction: incoming

- name: Allow incoming SSH connections
  community.general.ufw:
    rule: allow
    to_ip: any
    to_port: 22
    proto: any
    direction: in

- name: Enable ufw
  community.general.ufw:
    state: enabled

- name: Enable basic locales
  ansible.builtin.lineinfile:
    dest: /etc/locale.gen
    regexp: '^(#\s*)?{{ item }}\.UTF-8\s+UTF-8$'
    line: '{{ item }}.UTF-8 UTF-8'
    backup: true
  with_items:
    - C
    - en_US
  notify:
    - Regenerate locales

- name: Set default locale
  ansible.builtin.lineinfile:
    dest: /etc/locale.conf
    regexp: '^{{ item }}='
    line: '{{ item }}=C.UTF-8'
  with_items:
    - LANG
    - LC_ALL

- name: Keep UFW messages from being logged to files other than ufw.log
  ansible.builtin.lineinfile:
    dest: /etc/rsyslog.d/20-ufw.conf
    regexp: '^\s*#?\s*&\s+(~|stop)\s*$'
    line: '& stop'
    insertafter: EOF
    backup: true
  notify:
    - Restart rsyslog

- name: Give some syslog facilities their own logfiles
  ansible.builtin.lineinfile:
    dest: /etc/rsyslog.d/50-default.conf
    regexp: '^#?{{ item.key }}\s+{{ item.value }}$'
    line: '{{ item.key }} {{ item.value }}'
    mode: "0644"
    create: true
    backup: true
  with_dict:
    "cron.*": /var/log/cron.log
    "user.*": -/var/log/user.log
  notify:
    - Restart rsyslog

- name: Configure SSH
  ansible.builtin.copy:
    src: sshd.conf
    dest: /etc/ssh/sshd_config.d/99jwodder.conf
    owner: root
    mode: "0644"
  notify:
    - Restart SSHd

- name: Configure PAM to show the "Last login" and "Failed logins" messages
  ansible.builtin.lineinfile:
    dest: /etc/pam.d/sshd
    # Insert between the pam_env lines and the pam_selinux line
    insertafter: 'pam_env'
    line: "{{ item }}"
    backup: true
  with_items:
    # Note that the lines will & must appear in the opposite order in the
    # configured file.
    - 'session optional    pam_lastlog.so silent noupdate showfailed'
    - 'session [default=1] pam_lastlog.so nowtmp showfailed'

- name: Configure mail behavior on SSH login
  # This change accomplishes the following:
  # - Removes the default "noenv" option so that $MAIL is set
  # - Adds the "quiet" option so that no message is printed if the default
  #   $MAIL is empty
  ansible.builtin.lineinfile:
    dest: /etc/pam.d/sshd
    regexp: '^(session\s+optional\s+pam_mail\.so)'
    # The version of /etc/pam.d/sshd provided by the openssh-server package has
    # a couple lines marked with "# [1]", and this is one of them.  I don't
    # know what it's for, but I'm preserving it.
    line: '\1 standard quiet # [1]'
    backrefs: true
    backup: true

- name: Configure APT
  ansible.builtin.template:
    src: apt.conf
    dest: /etc/apt/apt.conf.d/99jwodder
    owner: root
    mode: "0644"

- name: Configure needrestart
  ansible.builtin.copy:
    src: needrestart.conf
    dest: /etc/needrestart/conf.d/99jwodder.conf
    owner: root
    mode: "0644"

- name: Enable unattended upgrades
  ansible.builtin.debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    vtype: boolean
    value: true
  notify:
    - Enable new unattended-upgrades settings

- name: Configure fail2ban
  ansible.builtin.copy:
    src: "fail2ban/{{ item }}"
    dest: "/etc/fail2ban/{{ item }}"
    owner: root
    mode: "0644"
    backup: true
  with_items:
    - fail2ban.d/dbpurgeage.local
    - jail.d/defaults.local
    - jail.d/recidive.local
    - jail.d/sshd.local
  notify:
    - Restart fail2ban

- name: Create journald.conf.d
  ansible.builtin.file:
    path: /etc/systemd/journald.conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Configure journald
  ansible.builtin.copy:
    src: journald.conf
    dest: /etc/systemd/journald.conf.d/jwodder.conf
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify:
    - Restart journald

- name: Set up admin user
  ansible.builtin.import_tasks: admin.yml

- name: Set up git user
  ansible.builtin.import_tasks: git.yml

- name: Set up attached drive
  ansible.builtin.import_tasks: partition.yml
  when: drive_id is defined
