---
- name: Determine drive name
  ansible.builtin.set_fact:
    base_drive_name: "{{ item.key }}"
  with_dict: "{{ ansible_facts['devices'] }}"
  when: "drive_id in (item.value.links.ids | default([]))"

- name: Assert that drive name was found
  ansible.builtin.assert:
    that: base_drive_name is defined
    fail_msg: "Could not find drive with ID {{ drive_id }}"

- name: Partition attached drive
  # Based on my reading of the module source, if the partition already exists
  # and the label & flags have the values given here, then — as long as
  # `resize` is set to `false` — nothing will be altered.
  community.general.parted:
    device: "/dev/disk/by-id/{{ drive_id }}"
    number: 1
    state: present
    resize: false
    flags: []
    label: gpt
    part_start: 0%
    part_end: 100%
    fs_type: ext4

- name: Format attached drive
  community.general.filesystem:
    dev: "/dev/disk/by-id/{{ drive_id }}-part1"
    fstype: ext4
  register: base_format

- name: Re-collect facts to get new device UUID  # noqa: no-handler
  ansible.builtin.setup:
    gather_subset: "!all,!min,devices"
  when: base_format is changed

- name: Create /srv
  ansible.builtin.file:
    path: /srv/git
    state: directory
    owner: root
    mode: "0755"

- name: Mount drive at /srv/git
  ansible.posix.mount:
    src: "UUID={{ ansible_facts['devices'][base_drive_name]['partitions'][base_drive_name + '1']['uuid'] }}"
    path: /srv
    fstype: ext4
    opts: defaults,nofail,discard
    dump: '0'
    passno: '0'
    state: mounted

- name: Create /srv/git and grant git user ownership of everything within
  ansible.builtin.file:
    path: /srv/git
    state: directory
    follow: false
    recurse: true
    owner: git
    mode: u+rwX

- name: Create /srv/scratch
  ansible.builtin.file:
    path: /srv/scratch
    state: directory
    owner: root
    mode: "01777"  # sticky + 0o777
