APT::Cache::AllVersions "false";
APT::Keep-Downloaded-Packages "false";

Unattended-Upgrade::Automatic-Reboot "false";
Unattended-Upgrade::InstallOnShutdown "false";
Unattended-Upgrade::Mail "{{ admin_user }}";
Unattended-Upgrade::MailOnlyOnError "false";
