APT::Cache::AllVersions "false";
APT::Keep-Downloaded-Packages "false";

Unattended-Upgrade::Automatic-Reboot "true";
Unattended-Upgrade::Automatic-Reboot-Time "03:13";
Unattended-Upgrade::Automatic-Reboot-WithUsers "false";
Unattended-Upgrade::Mail "{{ admin_user }}";
Unattended-Upgrade::MailReport "on-change";
