---
- name: Install thoth-utils for admin user
  community.general.pipx:
    name: jwodder-thoth-utils
    source: git+https://github.com/jwodder/thoth-utils
    state: latest
  become: true
  become_user: "{{ admin_user }}"
  notify:
    - Restart authfail.service if running

- name: Create ~admin/.config/thoth-utils
  ansible.builtin.file:
    path: "/home/{{ admin_user }}/.config/thoth-utils"
    state: directory
    owner: "{{ admin_user }}"
    mode: "0755"

- name: Create thoth-utils config file
  ansible.builtin.template:
    src: config.toml
    dest: "/home/{{ admin_user }}/.config/thoth-utils/config.toml"
    owner: "{{ admin_user }}"
    mode: "0600"

- name: Download & install Dropbox-Uploader
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/{{ dropbox_uploader_version }}/dropbox_uploader.sh
    dest: /usr/local/bin/dropbox_uploader
    owner: root
    mode: "0755"
    force: true

- name: Install age
  install_age:
    minversion: v1.3.0

- name: Install bin/mkbackup
  ansible.builtin.template:
    src: mkbackup
    dest: /usr/local/bin/mkbackup
    owner: root
    mode: "0755"

- name: Create /usr/local/etc/mkbackup
  ansible.builtin.file:
    path: /usr/local/etc/mkbackup
    state: directory
    owner: root
    mode: "0755"

- name: Install share/backup.exclude
  ansible.builtin.copy:
    src: backup.exclude
    dest: /usr/local/etc/mkbackup/backup.exclude
    owner: root
    mode: "0644"

- name: Store Dropbox credentials
  ansible.builtin.copy:
    dest: /usr/local/etc/mkbackup/dropbox_uploader
    content: |
      CONFIGFILE_VERSION=2.0
      OAUTH_APP_KEY={{ backup_dropbox_oauth_app_key | quote }}
      OAUTH_APP_SECRET={{ backup_dropbox_oauth_app_secret | quote }}
      OAUTH_REFRESH_TOKEN={{ backup_dropbox_oauth_app_refresh_token | quote }}
    owner: root
    group: root
    mode: "0600"

- name: Store backup recipient pubkey
  ansible.builtin.copy:
    dest: /usr/local/etc/mkbackup/backup-recipient.txt
    content: |
      {{ backup_recipient_pubkey }}
    owner: root
    mode: "0644"

- name: Configure systemd units
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/systemd/system/{{ item }}
    mode: "0644"
  with_items:
    - authfail.service
    - authfail.socket
    - authfail-vacuum.service
    - authfail-vacuum.timer
    - dailyreport.service
    - dailyreport.timer
    - gc-srv-git.service
    - gc-srv-git.timer
    - mkbackup.service
    - mkbackup.timer
    - update-dns.service
    - update-dns.timer
  register: services_units

# This has to run before we can enable stuff, so using a handler isn't an
# option here.
- name: Reload systemd  # noqa: no-handler
  ansible.builtin.systemd:
    daemon_reload: true
  when: services_units is changed

- name: Enable & start systemd timers & sockets
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - authfail.socket
    - authfail-vacuum.timer
    - dailyreport.timer
    - gc-srv-git.timer
    - mkbackup.timer
    - update-dns.timer

- name: Configure rsyslog to send failed SSH logins to FIFO
  ansible.builtin.template:
    src: 99-authfail.conf
    dest: /etc/rsyslog.d/99-authfail.conf
    owner: root
    mode: "0644"
    backup: true
  notify:
    - Restart rsyslog
